Raise awareness about partial Ranges support
As soon as we specify the bounds,
the data we fetch from the db is not what we expect

postgresql logs
```
statement: BEGIN
statement: INSERT INTO data_table (range) VALUES (daterange('2013-03-23'::date, '2013-03-24'::date, '()'))
statement: COMMIT
statement: SELECT data_table.range
	FROM data_table

```

test result
```
AssertionError: [(DateRange(empty=True),)] != [(DateRange(datetime.date(2013, 3, 23), datetime.date(2013, 3, 24), '()'),)]

```

Note, at this stage I'm not sure it is sqlalchemy or psycopg2 or myself responsibility