- add TypeError handling to the tests here, ensure TypeError for the control is a TypeError for the row, as is raised on py3k when less/greater operators are used on incompatible types