add postgres dialect alias
Why
===
* According to
https://www.prisma.io/dataguide/postgresql/short-guides/connection-uris?query=&page=1
a postgres URL can have a schema of "postgres" or "postgresql".
* Users who have a URL starting with "postgres://" cannot use sqlalchemy without
URL pre-processing, because they will see this error:

```
  File "/home/runner/UserAuth/.pythonlibs/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 375, in load
    raise exc.NoSuchModuleError(
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres
```
* Since postgres unambiguously means we want to use postgresql, we can
add a quick dialect alias to solve this UX problem

What changed
===
* If the dialect is "postgres", rewrite it to "postgresql".

Test plan
===
* Using SQLALCHEMY_DATABASE_URI env var with a "postgres://" URL now
works. I tested that that I can add a row to the database using sqlalchemy.