Include new MySQL error code 4031 for MySQL disconnect check
When using pool_pre_ping=True with MySQL version 8.0.28 and a stale
connection, SQLAlchemy raises the following error instead of
reconnecting:

MySQLdb._exceptions.OperationalError: (4031, 'The client was disconnected by the server because of inactivity. See wait_timeout and interactive_timeout for configuring this behavior.')

4031 (ER_CLIENT_INTERACTION_TIMEOUT) is a new error code added in
MySQL version 8.0.24:
https://dev.mysql.com/doc/mysql-errors/8.0/en/server-error-reference.html#error_er_client_interaction_timeout

This commit adds 4031 to the error codes list checked in MySQL dialect
"is_disconnect" check.

Fixes: #8036